// <auto-generated />
namespace ProjectManagmentTool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addeeddd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addeeddd));
        
        string IMigrationMetadata.Id
        {
            get { return "201802101430136_addeeddd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
